# Generated by Django 6.0.1 on 2026-06-15 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votingcampaign_results_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Voter's email address", max_length=254)),
                ('voter_code', models.CharField(help_text='Unique voter code', max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, help_text="Voter's full name", max_length=255)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional identification fields')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether voter has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['voter_code'],
            },
        ),
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this voter list', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the voter list')),
                ('csv_file', models.FileField(help_text='CSV file containing voter details', upload_to='voting/voter_lists/')),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_voters', models.PositiveIntegerField(default=0, help_text='Total number of voters in this list')),
            ],
            options={
                'verbose_name_plural': 'Voter Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Device fingerprint (for open voting mode)', max_length=255),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='device_tracking_method',
            field=models.CharField(choices=[('browser_fingerprint', 'Browser Fingerprinting'), ('ip_address', 'IP Address'), ('cookie', 'Cookie-based'), ('combined', 'Combined Methods')], default='browser_fingerprint', help_text='Method for tracking devices in open voting mode', max_length=20),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='enable_ip_restriction',
            field=models.BooleanField(default=False, help_text='Restrict voting by IP address in open voting mode'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='voting_mode',
            field=models.CharField(choices=[('open', 'Open Voting - No authentication required'), ('authenticated', 'Authenticated - Voter list required')], default='open', help_text='Is authentication required for voting?', max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, help_text='Voter record (for authenticated voting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='voting.voter'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voting.voterlist'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='voter_list',
            field=models.ForeignKey(blank=True, help_text='Associated voter list (required for authenticated voting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='voting.voterlist'),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('voter_list', 'email')},
        ),
    ]
