# Generated by Django 6.0.1 on 2026-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voter_voterlist_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcampaign',
            name='auth_help_text',
            field=models.TextField(default="If you don't have your voter code or have issues authenticating, please contact the election administrator.", help_text='Help text shown below the authentication form'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='auth_message',
            field=models.TextField(default='Please authenticate with your voter credentials to participate in this election.', help_text='Instructions for voter authentication'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='auth_title',
            field=models.CharField(default='Verify Your Identity', help_text='Title for voter authentication section', max_length=200),
        ),
    ]
