# Generated by Django 6.0.1 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_votingcampaign_auth_help_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcampaign',
            name='auth_submit_label',
            field=models.CharField(default='Verify & Proceed to Voting', help_text='Label for authentication submit button', max_length=100),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='voter_code_label',
            field=models.CharField(default='Voter Code', help_text='Label for voter code field', max_length=100),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='voter_email_label',
            field=models.CharField(default='Email Address', help_text='Label for email field', max_length=100),
        ),
    ]
