# Generated by Django 6.0.1 on 2026-06-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_votingcampaign_auth_submit_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the achievement', max_length=255)),
                ('description', models.TextField(help_text='Description of the achievement')),
                ('icon', models.CharField(default='fa-star', help_text='FontAwesome icon class (e.g., fa-star, fa-trophy, fa-medal)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='voting.candidate')),
            ],
            options={
                'verbose_name_plural': 'Candidate Achievements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Activity photo', upload_to='voting/candidates/activities/')),
                ('caption', models.CharField(blank=True, help_text="Photo caption (e.g., 'Community event', 'Project completion')", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity')),
                ('activity_type', models.CharField(choices=[('event', 'Community Event'), ('project', 'Project/Work'), ('achievement', 'Achievement'), ('initiative', 'Initiative'), ('other', 'Other')], default='event', help_text='Type of activity', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_photos', to='voting.candidate')),
            ],
            options={
                'verbose_name_plural': 'Candidate Activity Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('tiktok', 'TikTok Video'), ('video_file', 'Video File Upload'), ('other', 'Other Video Link')], default='youtube', help_text='Type of media', max_length=50)),
                ('title', models.CharField(help_text='Title of the video/media', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the video/media')),
                ('embed_url', models.URLField(blank=True, help_text='URL to the video (YouTube link, TikTok link, etc.)')),
                ('video_file', models.FileField(blank=True, help_text='Video file upload (MP4, WebM, etc.)', upload_to='voting/candidates/videos/')),
                ('youtube_video_id', models.CharField(blank=True, help_text='YouTube video ID (auto-extracted)', max_length=100)),
                ('tiktok_video_id', models.CharField(blank=True, help_text='TikTok video ID (auto-extracted)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='voting.candidate')),
            ],
            options={
                'verbose_name_plural': 'Candidate Media',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
