# Generated by Django 6.0.1 on 2026-07-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_candidateachievement_candidateactivityphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this voter is authorized for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='voting.votingcampaign'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_code',
            field=models.CharField(blank=True, help_text='Unique voter code', max_length=100, unique=True),
        ),
    ]
