# Generated by Django 5.2.2 on 2026-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voter_campaign_alter_voter_voter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_code',
            field=models.CharField(help_text='Unique voter code', max_length=100, unique=True),
        ),
    ]
