# Generated by Django 6.0.1 on 2026-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blogpost_event_date_blogpost_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog/photos/'),
        ),
    ]
