# Generated by Django 6.0.1 on 2026-06-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
