# Generated by Django 6.0.1 on 2026-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_event_category_ticketcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
